# Generated by Django 4.2.13 on 2024-06-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Perguntax', 'verbose_name_plural': 'Perguntasx'},
        ),
    ]
