# Generated by Django 4.2.13 on 2024-06-26 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choices'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Choices',
            new_name='Choice',
        ),
    ]
