"""
Django settings for webapp project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from decouple import config
import os
from django.contrib.messages import constants as messages
from dotenv import load_dotenv

load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = 'django-insecure-x^wjj^)sdw8qi)__0n!@szcy_ih)1ut^d*bx1sd#=l4sofie6v'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True #False #gunTrue
DEBUG = os.environ.get('DJANGO_DEBUG', default=0)
print(f'\nDEBUG {DEBUG}')

#ALLOWED_HOSTS = ['127.0.0.1', 'localhost']
ALLOWED_HOSTS = str(os.environ.get('DJANGO_ALLOWED_HOSTS')).split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'webapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'webapp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.mysql",
#        "NAME": "django_do_zero_db",
#        "USER": "root",
#        "PASSWORD": "root",
#        "HOST": "127.0.0.1",
#        "PORT": "3306",
#    }
#}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#-------------------------------------------------------------------------
# CONFIGURACOES DO PROJETO
#-------------------------------------------------------------------------

INSTALLED_APPS += ['polls.apps.PollsConfig', 'accounts.apps.AccountsConfig',]

TEMPLATES[0]['DIRS'] += ['templates',]

STATIC_ROOT = os.path.join(BASE_DIR, 'public')
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static'), ]

LOGIN_REDIRECT_URL = '/ola'
LOGOUT_REDIRECT_URL = '/ola'

MESSAGE_TAGS = {
    messages.DEBUG: 'secundary',
    messages.INFO: 'info',
    messages.SUCCESS: 'success',
    messages.WARNING: 'warning',
    messages.ERROR: 'danger',
}

AUTH_USER_MODEL = 'accounts.CustomUser'

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'public/')

#Emails
DEFAULT_FROM_EMAIL="jramalho.reis@gmail.com"
#if DEBUG == True:
#    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#else:
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
#EMAIL_HOST = 'smtp.gmail.com'
#EMAIL_PORT = '587'
#EMAIL_USE_TLS = True
#EMAIL_HOST_USER = 'jramalho.reis@gmail.com'
#EMAIL_HOST_PASSWORD = 'Mnv9569-@195'
#EMAIL_HOST_PASSWORD = 'luaa rqhy ejle hfuv' (senha de app#)

EMAIL_HOST = config('EMAIL_HOST')
EMAIL_PORT = config('EMAIL_PORT')
EMAIL_USE_TLS = config('EMAIL_USE_TLS')
EMAIL_HOST_USER = config('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD')

MAX_CHOICES_PER_QUESTION = 3



"""
print(f'--------------------------------------')
print(f'Configuracoes do Projeto Polls x')
print(f'--------------------------------------')
print(f'BASE_DIR ...................: {BASE_DIR}')
print(f'SECRET_KEY .................: {SECRET_KEY}')
print(f'DEBUG ......................: {DEBUG}')
print(f'ALLOWED_HOSTS...............: {ALLOWED_HOSTS}')
print(f'INSTALLED_APPS .............: {INSTALLED_APPS}')
print(f'MIDDLEWARE .................: {MIDDLEWARE}')
print(f'ROOT_URLCONF ...............: {ROOT_URLCONF}')
print(f'TEMPLATES ..................: {TEMPLATES}')
#print(f'TEMPLATES ..................: {TEMPLATES[0].get("DIRS")}')
print(f'WSGI_APPLICATIONS ..........: {WSGI_APPLICATION}')
print(f'DATABASES ..................: {DATABASES}')
print(f'AUTH_PASSWORD_VALIDADATORS..: {AUTH_PASSWORD_VALIDATORS}')
print(f'LANGUAGE_CODE ..............: {LANGUAGE_CODE}')
print(f'TIME_ZONE ..................: {TIME_ZONE}')
print(f'USE_I18N ...................: {USE_I18N}')
print(f'USE_TZ .....................: {USE_TZ}')
print(f'STATIC_URL .................: {STATIC_URL}')
print(f'DEFAULT_AUTO_FIELD .........: {DEFAULT_AUTO_FIELD}')
print(f'STATIC_ROOT ................: {STATIC_ROOT}')
print(f'STATICFILES_DIRS............: {STATICFILES_DIRS}')
print(f'LOGIN_REDIRECT_URL..........: {LOGIN_REDIRECT_URL}')
print(f'LOGOUT_REDIRECT_URL.........: {LOGOUT_REDIRECT_URL}')
print(f'AUTH_USER_MODEL.............: {AUTH_USER_MODEL}')

print(f'MEDIA_URL...................: {MEDIA_URL}')
print(f'MEDIA_ROOT..................: {MEDIA_ROOT}')

print(f'DEFAULT_FROM_EMAIL..........: {DEFAULT_FROM_EMAIL}')
print(f'EMAIL_BACKEND...............: {EMAIL_BACKEND}')
print(f'EMAIL_HOST..................: {EMAIL_HOST}')
print(f'EMAIL_PORT..................: {EMAIL_PORT}')
print(f'EMAIL_USE_TLS...............: {EMAIL_USE_TLS}')
print(f'EMAIL_HOST_USER.............: {EMAIL_HOST_USER}')
print(f'EMAIL_HOST_PASSWORD.........: {EMAIL_HOST_PASSWORD}')
"""


